Reflectively invoke RowMetadata.getColumnMetadatas.
We now use reflection to call RowMetadata.getColumnMetadatas to avoid NoSuchMethodError when using R2DBC 0.9 as the return type has changed in newer R2DBC versions.

Closes #699